name: Terraform Spoke VPC

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::434097521299:role/testingdummy
          aws-region: ap-south-1

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: terraform1

      - name: Terraform Init
        run: terraform init
        working-directory: terraform1


      - name: Show Files
        run: |
           pwd
           ls -la
           find . -name "*.tf"  

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform1

      - name: Terraform Plan
        run: terraform plan 
        working-directory: terraform

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve tfplan
        working-directory: terraform1   